apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taller-docker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taller-docker-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 120